---
title: "Data Science in the Statistics Curricula: Preparing Students to 'Think with Data'"
author: "Johanna Hardin, Roger Hoerl, Nicholas J. Horton, and Deborah Nolan"
date: "April 5, 2015"
output: html_document
---


### Curriculum materials
  
  * [Integrating Computing into the Statistics Curricula](http://www.stat.berkeley.edu/~statcur): Nolan and Temple Lang (UC/Berkeley)
  * [Introduction to Big Data Analysis](http://llc.stat.purdue.edu/2014/29000/index.html): Mark Ward (Purdue)
  * [Computer Science for Mathematicians and Scientists (CS125)](http://www.cs.stolaf.edu/wiki/index.php/CS125_F13): Roback and Hall-Holt (St. Olaf College)
  * [Introduction to Data Technologies](https://www.stat.auckland.ac.nz/~paul/ItDT): Paul Murrell (University of Auckland)
  * [Data Science Specialization](https://www.coursera.org/specialization/jhudatascience/1) (Johns Hopkins University)
  * [Data Computing Fundamentals 2014](http://dtkaplan.github.io/DCF-Course-2014/): Kaplan (Macalester College) ([2013 materials](http://rpubs.com/dtkaplan/DCF-Spring2013-Syllabus)) plus sample [Restaurant violations](RestaurantViolations.pdf) activity
  * [Swirl: Learn R, in R](http://swirlstats.com)
  * [Data Science in R](http://www.crcpress.com/product/isbn/9781482234817): Nolan and Temple Lang (CRC Press)
  * [XML and Web Technologies for Data Sciences with R](http://www.springer.com/us/book/9781461478997): Nolan and Temple Lang (Springer)

### Papers and related resources
  
  * [Data science in the statistics curriculum ](http://arxiv.org/abs/1410.3127): Hardin et al (arXiv.org)
  * [Computing in the statistics curriculum](http://www.stat.berkeley.edu/~statcur/Preprints/ComputingCurric3.pdf): Nolan and Temple Lang (TAS 2010)
  * [Setting the stage for data science: integration of data management skills in introductory and second courses in statistics](http://arxiv.org/abs/1502.00318): Horton, Baumer, and Wickham (arXiv.org) plus [examples and activities](http://www.amherst.edu/~nhorton/precursors)
  * American Statistical Association 2014 [Curriculum Guidelines ](http://www.amstat.org/education/curriculumguidelines.cfm) for Undergraduate Programs in Statistics
  * [A data science course for undergraduates](http://arxiv.org/abs/1503.05570): Baumer (arXiv.org)
  * [Teaching and learning data visualization: ideas and assignments](http://arxiv.org/abs/1503.00781): Nolan and Perrett (arXiv.org)
 
  